#!/usr/bin/env bash
# Xavani Agent installer — generated by scripts/generate_installers.py (F03).
# Installs the release archive into $XAVANI_HOME (default ~/.xavani).
set -euo pipefail

VERSION="0.7.2"
ARCHIVE="xavani-0.7.2.tar.gz"
URL="https://github.com/enternovate/xavani-agent/releases/download/${ARCHIVE}"

XAVANI_HOME="${XAVANI_HOME:-$HOME/.xavani}"
BIN_DIR="$XAVANI_HOME/bin"
mkdir -p "$BIN_DIR"

echo "▶ Downloading Xavani $VERSION..."
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT
if command -v curl >/dev/null 2>&1; then
  curl -fsSL "$URL" -o "$TMPDIR/$ARCHIVE"
elif command -v wget >/dev/null 2>&1; then
  wget -q "$URL" -O "$TMPDIR/$ARCHIVE"
else
  echo "error: need curl or wget" >&2
  exit 1
fi

echo "▶ Extracting..."
tar -xzf "$TMPDIR/$ARCHIVE" -C "$BIN_DIR"

echo "✓ Installed to $BIN_DIR"
echo "  Add to PATH:  export PATH="$BIN_DIR:$PATH""
echo "  Run:          $BIN_DIR/xavani"
