# Xavani Agent installer — generated by scripts/generate_installers.py (F03).
# Installs the release archive into $env:XAVANI_HOME (default ~/.xavani).
$ErrorActionPreference = "Stop"

$Version = "0.7.2"
$Archive = "xavani-0.7.2.zip"
$Url = "https://github.com/enternovate/xavani-agent/releases/download/$Archive"

$XavaniHome = if ($env:XAVANI_HOME) { $env:XAVANI_HOME } else { Join-Path $HOME ".xavani" }
$BinDir = Join-Path $XavaniHome "bin"
New-Item -ItemType Directory -Force -Path $BinDir | Out-Null

Write-Host "▶ Downloading Xavani $Version..."
$Tmp = Join-Path $env:TEMP "xavani-install-$([guid]::NewGuid())"
New-Item -ItemType Directory -Force -Path $Tmp | Out-Null
try {
  Invoke-WebRequest -Uri $Url -OutFile (Join-Path $Tmp $Archive)
  Expand-Archive -Path (Join-Path $Tmp $Archive) -DestinationPath $BinDir -Force
} finally {
  Remove-Item -Recurse -Force $Tmp
}

Write-Host "✓ Installed to $BinDir"
Write-Host "  Add to PATH:  `$env:PATH = `"$BinDir;`$env:PATH`""
Write-Host "  Run:          `$BinDir\xavani.exe"
