#!/usr/bin/env python3
"""Generate bash/zsh/fish completion scripts for the ``xavani`` binary.

Source of truth: the CLI's OWN slash-command registry —
``xavani_cli.commands.COMMAND_REGISTRY``. That registry is the same data
the ``/help`` command renders (via ``COMMANDS_BY_CATEGORY``) and the
docstring there declares it the single source of truth consumed by CLI
help, gateway dispatch, and autocomplete, so completions stay in lockstep
with the running binary without hand-maintaining flags.

Only ``cli_only`` and general commands are emitted (``gateway_only``
commands are invisible to the terminal CLI). Aliases and CLI shortcuts
are included as completion candidates.

Usage:
    python3 scripts/gen_completions.py [--outdir scripts/completions]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from xavani_cli.commands import COMMAND_REGISTRY  # noqa: E402


def command_names() -> list[str]:
    names: list[str] = []
    for cmd in COMMAND_REGISTRY:
        if cmd.gateway_only:
            continue
        names.append(f"/{cmd.name}")
        names.extend(f"/{alias}" for alias in cmd.aliases)
        names.extend(f"/{alias}" for alias in cmd.cli_aliases)
        if cmd.subcommands:
            names.extend(f"/{cmd.name} {sub}" for sub in cmd.subcommands)
    return sorted(set(names))


def bash_script(commands: list[str]) -> str:
    quoted = " ".join(f"'{c}'" for c in commands)
    return f"""# bash completion for xavani (generated by scripts/gen_completions.py)
_xavani_completions() {{
    local cur prev
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    prev="${{COMP_WORDS[COMP_CWORD-1]}}"
    local base="${{cur%% *}}"
    local words="{quoted}"
    if [[ "$cur" == *" "* ]]; then
        local candidates
        candidates=$(printf '%s\\n' $words | grep -F -- "${{base}} " | sed "s/^${{base}} //")
        COMPREPLY=( $(compgen -W "$candidates" -- "${{cur##* }}") )
    else
        COMPREPLY=( $(compgen -W "$words" -- "$cur") )
    fi
}}
complete -F _xavani_completions xavani
"""


def zsh_script(commands: list[str]) -> str:
    quoted = " ".join(f"'{c}'" for c in commands)
    return f"""#compdef xavani
# zsh completion for xavani (generated by scripts/gen_completions.py)
# Slash commands derived from xavani_cli.commands.COMMAND_REGISTRY.
_xavani_commands=({quoted})

_xavani() {{
    local -a cmds
    cmds=($_xavani_commands)
    _describe 'command' cmds
}}

if [ "$funcstack[1]" = "_xavani" ]; then
    _xavani "$@"
else
    compdef _xavani xavani
fi
"""


def fish_script(commands: list[str]) -> str:
    lines = ["# fish completion for xavani (generated by scripts/gen_completions.py)"]
    for cmd in commands:
        lines.append(f"complete -c xavani -f -a '{cmd}'")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--outdir",
        type=Path,
        default=REPO_ROOT / "scripts" / "completions",
        help="output directory (default: scripts/completions)",
    )
    args = parser.parse_args()

    commands = command_names()
    targets = {
        "bash": args.outdir / "bash" / "xavani.bash",
        "zsh": args.outdir / "zsh" / "_xavani",
        "fish": args.outdir / "fish" / "xavani.fish",
    }
    scripts = {
        "bash": bash_script(commands),
        "zsh": zsh_script(commands),
        "fish": fish_script(commands),
    }
    for shell, path in targets.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(scripts[shell], encoding="utf-8")
        print(f"wrote {path} ({len(commands)} commands)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
