#!/usr/bin/env python3
# Copyright (c) 2025-2026 Enternovate.
# MIT License -- See LICENSE file for full terms.
# Built by Enternovate -- Open source. Private. Local.

"""F03: native installer generator.

Generates platform-native installer scripts (bash for POSIX, PowerShell
for Windows) that install the release archive to the user's XAVANI_HOME
and create the desktop launcher. The generator is deterministic —
given the same release metadata, it produces byte-identical scripts —
so CI can diff generated output against committed goldens.

Usage:
    python3 scripts/generate_installers.py --version 0.7.2 --out dist/installers
    python3 scripts/generate_installers.py --check   # compare against goldens
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Dict

REPO_ROOT = Path(__file__).resolve().parent.parent
GOLDEN_DIR = REPO_ROOT / "scripts" / "installer_goldens"

_BASH_TEMPLATE = """#!/usr/bin/env bash
# Xavani Agent installer — generated by scripts/generate_installers.py (F03).
# Installs the release archive into $XAVANI_HOME (default ~/.xavani).
set -euo pipefail

VERSION="{version}"
ARCHIVE="xavani-{version}.tar.gz"
URL="{base_url}/${{ARCHIVE}}"

XAVANI_HOME="${{XAVANI_HOME:-$HOME/.xavani}}"
BIN_DIR="$XAVANI_HOME/bin"
mkdir -p "$BIN_DIR"

echo "▶ Downloading Xavani $VERSION..."
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT
if command -v curl >/dev/null 2>&1; then
  curl -fsSL "$URL" -o "$TMPDIR/$ARCHIVE"
elif command -v wget >/dev/null 2>&1; then
  wget -q "$URL" -O "$TMPDIR/$ARCHIVE"
else
  echo "error: need curl or wget" >&2
  exit 1
fi

echo "▶ Extracting..."
tar -xzf "$TMPDIR/$ARCHIVE" -C "$BIN_DIR"

echo "✓ Installed to $BIN_DIR"
echo "  Add to PATH:  export PATH=\"$BIN_DIR:$PATH\""
echo "  Run:          $BIN_DIR/xavani"
"""

_PS1_TEMPLATE = """# Xavani Agent installer — generated by scripts/generate_installers.py (F03).
# Installs the release archive into $env:XAVANI_HOME (default ~/.xavani).
$ErrorActionPreference = "Stop"

$Version = "{version}"
$Archive = "xavani-{version}.zip"
$Url = "{base_url}/$Archive"

$XavaniHome = if ($env:XAVANI_HOME) {{ $env:XAVANI_HOME }} else {{ Join-Path $HOME ".xavani" }}
$BinDir = Join-Path $XavaniHome "bin"
New-Item -ItemType Directory -Force -Path $BinDir | Out-Null

Write-Host "▶ Downloading Xavani $Version..."
$Tmp = Join-Path $env:TEMP "xavani-install-$([guid]::NewGuid())"
New-Item -ItemType Directory -Force -Path $Tmp | Out-Null
try {{
  Invoke-WebRequest -Uri $Url -OutFile (Join-Path $Tmp $Archive)
  Expand-Archive -Path (Join-Path $Tmp $Archive) -DestinationPath $BinDir -Force
}} finally {{
  Remove-Item -Recurse -Force $Tmp
}}

Write-Host "✓ Installed to $BinDir"
Write-Host "  Add to PATH:  `$env:PATH = `"$BinDir;`$env:PATH`""
Write-Host "  Run:          `$BinDir\\xavani.exe"
"""


def generate_installers(
    version: str,
    base_url: str = "https://github.com/enternovate/xavani-agent/releases/download",
) -> Dict[str, str]:
    """Generate installer scripts. Returns {filename: content}."""
    return {
        "install.sh": _BASH_TEMPLATE.format(version=version, base_url=base_url),
        "install.ps1": _PS1_TEMPLATE.format(version=version, base_url=base_url),
    }


def check_goldens(version: str) -> bool:
    """Compare generated scripts against the committed goldens."""
    generated = generate_installers(version)
    ok = True
    for filename, content in generated.items():
        golden = GOLDEN_DIR / filename
        if not golden.exists():
            print(f"MISSING golden: {golden}", file=sys.stderr)
            ok = False
            continue
        if golden.read_text(encoding="utf-8") != content:
            print(f"DRIFT: {filename} differs from golden", file=sys.stderr)
            ok = False
    return ok


def main() -> int:
    parser = argparse.ArgumentParser(description="Xavani native installer generator")
    parser.add_argument("--version", required=True, help="release version (e.g. 0.7.2)")
    parser.add_argument("--out", type=Path, default=None, help="output directory")
    parser.add_argument("--check", action="store_true", help="compare against goldens")
    parser.add_argument("--base-url", default=None, help="release base URL")
    args = parser.parse_args()

    if args.check:
        return 0 if check_goldens(args.version) else 1

    base_url = args.base_url or "https://github.com/enternovate/xavani-agent/releases/download"
    generated = generate_installers(args.version, base_url)
    out_dir = args.out or (REPO_ROOT / "dist" / "installers")
    out_dir.mkdir(parents=True, exist_ok=True)
    for filename, content in generated.items():
        path = out_dir / filename
        path.write_text(content, encoding="utf-8")
        print(f"✓ wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
